### ISSUE TITLE
DeadLock and Rule Issue

### ISSUE THREAD

**Issue by synchronisator** [balzamas/eilemitweile#21]
Hi,

nice game.
I run into two issues.
1) Deadlock at some point in the game, i dont know why:
![Bildschirmfoto zu 2023-01-25 10-08-11](https://user-images.githubusercontent.com/10772789/214528627-b5789a0c-a700-428f-aced-c27df658326e.png)
I cant move and the game stuck.

2) i think the "block" is not like descriped in the rules 
https://de.wikipedia.org/wiki/Eile_mit_Weile
The block should block all tokens in front of the blockfield. There should not be more than two tokens on the field at the bottom rigth. 

Maybe a popup with the rules of the game would be nice, i had to look in wikipedia how the game works :)

But its a nice little game :) Thanks

**Comment by balzamas** [comment]
The blocking on the benches is not finished. In general it is possible to go on the bench but not further. But it's played different in every family, definitely needs explanation! (or option which rule to use!).

About the dead lock: before submitting, did you roll the dice again? 

Thank you very much for the feedback!

**Comment by synchronisator** [comment]
The Daedlock was not real. I didnt understand that there is en extra roll after a 12. so i thought the game stuck.
